### ISSUE TITLE
SyntaxError when trying to change the network location using the wigle api 

### ISSUE THREAD

**Issue by Juandurdaneta** [adamhrv/skylift#11]
```
  File "skylift/cli_jobs.py", line 102
    jobs['run'] = jobs['run'].fillna(0)astype('int')
                                            ^
SyntaxError: invalid syntax
```
I get this SyntaxError whenever i try to get Wi-Fi data from Wigle by doing:
```
python skylift/cli_jobs.py wigle_api --wigle_api_name [my_user_name] --wigle_api_key [my_api_key] --jobs data/jobs/wigle_api.csv
```

**Comment by Delivers** [comment]
try: 

jobs['run'] = jobs['run'].fillna(0).astype('int')

**Comment by xfrozt54** [comment]
I got same problem but different error. The terminal showing :

  return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'notes'

**Comment by Delivers** [comment]
in skylift/cli_jobs.py uncommand:

 #jobs['venue_name'] = jobs['venue_name'].fillna('').astype('str')
 #jobs['notes'] = jobs['notes'].fillna('').astype('str')

and in skylift-master/skylift/app/geo_utils.py change:

geopy.distance.vincenty to geopy.distance.geodesic

**Comment by adamhrv** [comment]
Thanks. Will apply this update once the new Wigle API command is rebuilt. For now the project is only using a simplified CLI that:
- converts scan output (as a CSV) from Wigle (on Android) or Airport Utility (on iOS) to a networks JSON file
- converts the JSON file to an Arduino sketch for the ESP32 or ESP8266 (low-cost NodeMCU ESP version)
