### ISSUE TITLE
Open Discussion

### ISSUE THREAD

**Issue by adamhrv** [adamhrv/skylift#16]
Does this still work for you? What were your optimal conditions for spoofing? Did you experiment with different packet structures? 

Last time I tested was about a year ago and had limited, but functional, results using about 12 networks (relocated my phone to Peter Thiel’s Hawaiian vacation house ( https://ahprojects.com/datapools) ![](https://ahprojects.com/docs/archive/datapools/IMG_0926.PNG). This test was done indoors with other WiFi networks nearby, but it seems to work best when the GPS signals are attenuated (eg in a basement) and when the nearby WiFi signals are weak (< -80dbm) and sparse. Also, I didn't use Bluetooth iBeacons but that could be an interesting area to improve since the ESP32 does both BT and WiFi.

**Comment by TylerSharpe11** [comment]
Is there a way to ignore the real networks around you? it seems like I might have a problem there.

**Comment by adamhrv** [comment]
They can't really be ignored. Depending on your environment you may be able to shield the unwanted signals by with a thin conducting metal. Aluminum tape or similar thickness foil is effective low-cost shielding. However shielding materials reflect the signal so it's important which way it is deflected. Water and some carbon materials can act as absorbers, in effect transferring the RF signal energy into thermal energy.
