### ISSUE TITLE
Unable to upload demo, error displayed

### ISSUE THREAD

**Issue by ppo890** [adamhrv/skylift#17]
In file included from C:\skylift\archive\arduino\skylift_demo\skylift_demo.ino:39:
display.h:9:10: fatal error: Adafruit_SSD1306.h: No such file or directory
    9 | #include <Adafruit_SSD1306.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1
Adafruit_SSD1306.h: No such file or directory

**Comment by adamhrv** [comment]
Install https://github.com/adafruit/Adafruit_SSD1306 library
