### ISSUE TITLE
gerber files

### ISSUE THREAD

**Issue by jgrover** [adamhrv/skylift#3]
Tried to order the recommended PCB in the BOM file through seeed studio. Seeed requires gerber files and I believe the specs in this project are in Eagle format. Suggest providing a gerberfiles.zip to folks for convenience...

**Comment by Suzhou65** [comment]
> Tried to order the recommended PCB in the BOM file through seeed studio. Seeed requires gerber files and I believe the specs in this project are in Eagle format. Suggest providing a gerberfiles.zip to folks for convenience...

Hi,
I Download Autodesk Eagle, print out it's schematic and footprint, and using KiCad redesign it, plot to Gerber files, enjoy it.

[Gerber_SkyLift.zip](https://github.com/Suzhou65/Suzhou65.github.io/raw/master/lib_circuit/Gerber_SkyLift.zip)

**Comment by adamhrv** [comment]
Thanks!
