### ISSUE TITLE
Missing docs, and Data processing Issue

### ISSUE THREAD

**Issue by Suzhou65** [adamhrv/skylift#4]
At the chapter [ Setting up SkyLift ], the step about [ Python environment ] show page missing.

Also, I have no idea how to processing the data I has already collecting by Airport Utility, the Airport Utility will output text files including SSID, BSS, RSSI, Channel and times.

The question is, [ how to processing the data?], did I need convert Airport Utility text file to CSV format file, then using the python program in chapter [ Wigle API Jobs ] to output JSON files?

Thanks

**Comment by adamhrv** [comment]
I understand the workflow is not very intuitive. Since the spoofing seems to still be working, I'll work on adding an improved Click CLI interface during the next week.
The current parser is for iOS Wi-Fi scan utility, which is formatted as CSV.

**Comment by Suzhou65** [comment]
Thanks, I was amazed that this project is still working and updating, hope after workflow update my SkyLift can work perfectly

![SkyLift](https://i.imgur.com/JdiZcea.jpg)

**Comment by Suzhou65** [comment]
Amazing that project still updating and improve documents, great thanks.

I have redesign the PCB, let it more sleek and easier to soldering.

Adding case to protect the concept, the case is separate to three parts, using 3mm thickness acrylic plate and heat staking insert, headless screw is recommended.

This is final product looks like.  
![Imgur](https://i.imgur.com/hAU1Kbq.jpg)

* [PCB Gerber file](https://github.com/Suzhou65/Suzhou65.github.io/blob/master/lib_circuit/gerber_fakegps_skylift.zip)
* [Case CAD file](https://github.com/Suzhou65/Suzhou65.github.io/blob/master/lib_circuit/cad_fakegps_skylift.ait)
